"""FastAPI entrypoint for the unified-search connector.

Same observable contract as the previous Express server: ``GET /search?q=``
fans out in real time to Matrix/Seafile/Vikunja/Grommunio, relaying the
user's Keycloak Bearer token as-is (study 2.2 lines 391, 394) - this
connector never authenticates itself in place of the user.
"""

from __future__ import annotations

import json
import os

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from app.auth import InvalidToken, groups_from_claims, verify_token
from app.fanout import fan_out_search, merge_results
from app.sources.grommunio import search_grommunio
from app.sources.matrix import search_matrix
from app.sources.seafile import search_seafile
from app.sources.vikunja import search_vikunja

PORT = int(os.environ.get("PORT", "4002"))
TIMEOUT_MS = int(os.environ.get("SEARCH_TIMEOUT_MS", "2000"))
# GENERATED by scripts/sync_platform.py from platform.yaml's `portal.groups`
# (study 2.3) - do not hand-edit the value in the k8s manifest, change
# platform.yaml and re-run that script instead.
PORTAL_GROUPS = json.loads(os.environ.get("PORTAL_GROUPS_JSON", "[]"))

app = FastAPI(title="unified-search")


@app.get("/portal/apps")
async def portal_apps(request: Request):
    """Cross-cutting app-portal banner (study 2.3): which apps the caller's
    Keycloak group(s) grant them, read from the `groups` claim of the
    `libre365-portal` client's own token (see app/auth.py) - falls back to
    whichever group has "default: true" if the caller has no group of its
    own yet (a real gap in provisioning, not silently denying the menu)."""
    try:
        claims = verify_token(request.headers.get("authorization") or "")
    except InvalidToken as err:
        return JSONResponse(status_code=401, content={"error": str(err)})

    caller_groups = set(groups_from_claims(claims))
    matching = [g for g in PORTAL_GROUPS if g["name"] in caller_groups]
    if not matching:
        matching = [g for g in PORTAL_GROUPS if g.get("default")]

    seen: set[str] = set()
    apps = []
    for group in matching:
        for app_entry in group.get("apps", []):
            if app_entry["key"] not in seen:
                seen.add(app_entry["key"])
                apps.append(app_entry)

    return {"apps": apps}


@app.get("/search")
async def search(request: Request):
    query = (request.query_params.get("q") or "").strip()
    if not query:
        return JSONResponse(status_code=400, content={"error": "missing query parameter 'q'"})

    # The user's Keycloak Bearer token is relayed as-is (study 2.2 lines 391,
    # 394) to each source service: this connector never authenticates itself
    # with Matrix/Seafile/Vikunja/Grommunio in place of the user.
    auth_header = request.headers.get("authorization") or ""
    user_token = auth_header[7:] if auth_header.lower().startswith("bearer ") else auth_header
    if not user_token:
        return JSONResponse(
            status_code=401,
            content={"error": "missing Authorization: Bearer <token> header"},
        )

    outcomes = await fan_out_search(
        query,
        user_token,
        {
            "matrix": search_matrix,
            "seafile": search_seafile,
            "vikunja": search_vikunja,
            "grommunio": search_grommunio,
        },
        TIMEOUT_MS,
    )

    return {
        "query": query,
        "sources": [
            {
                "source": o.source,
                "ok": o.ok,
                "tookMs": o.took_ms,
                "error": o.error,
                "count": len(o.results),
            }
            for o in outcomes
        ],
        "results": [r.to_dict() for r in merge_results(outcomes)],
    }


@app.get("/healthz")
async def healthz():
    return {"status": "ok"}


def run() -> None:
    import uvicorn

    uvicorn.run("app.main:app", host="0.0.0.0", port=PORT)


if __name__ == "__main__":
    run()
