#!/usr/bin/env bash
# libre365 - makes the k3d dev cluster's CoreDNS resolve every Caddy-fronted
# platform.yaml domain (sso.libre365.example.org, seafile's, etc.) to the
# in-cluster `caddy-dev` Service, instead of failing outright.
#
# Why this exists (see docs/oidc.md for the full story): every component's
# OIDC configuration (Keycloak's own KC_HOSTNAME, Seafile/Vikunja/Synapse's
# issuer/authurl, the two oauth2-proxy gates' oidc-issuer-url) uses the real
# public domain unconditionally - the SAME value in production and dev,
# deliberately never hard-coded to a dev-only alternative. In production
# that domain is populated by external-dns against real DNS; this local k3d
# cluster has none, so a pod trying to reach it (Keycloak's own discovery
# document generation, oauth2-proxy's OIDC client at startup, an app's
# server-side token exchange) would otherwise fail to resolve it at all.
#
# CoreDNS's own `hosts` plugin supports inline entries directly in the
# Corefile (no external file needed) - this is CoreDNS's own documented
# mechanism for exactly this kind of local override, not something specific
# to this repo. Idempotent: entries are written between two marker
# comments, replaced (not duplicated) on every re-run - safe to call from
# deploy.sh on every invocation, matching this directory's existing
# idempotency convention.
#
# Unverified from this sandboxed environment (no live k3d cluster
# available here to actually run this against): the exact k3d/Rancher
# default Corefile layout this sed-based insertion assumes (a `.:53 {`
# block whose FIRST line is a plugin directive - k3d's shipped default at
# the time of writing) - inspect
# `kubectl get configmap coredns -n kube-system -o yaml` and adjust the
# insertion point below if a future k3d version's default Corefile differs.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

NAMESPACE="${1:-libre365}"
MARKER_BEGIN="# --- libre365-dev hosts (generated by patch-coredns-hosts.sh, do not edit) ---"
MARKER_END="# --- end libre365-dev hosts ---"

CADDY_DEV_IP=$(kubectl get service caddy-dev -n "$NAMESPACE" -o jsonpath='{.spec.clusterIP}')
if [ -z "$CADDY_DEV_IP" ]; then
  echo "    ! caddy-dev Service has no ClusterIP yet - apply infra/k8s/manifests/dev/caddy.yaml first." >&2
  exit 1
fi

# Domains read from platform.yaml (never hard-coded here) - every subdomain
# EXCEPT the ones DOMAINS_WITHOUT_CADDY_SITE already documents as
# legitimately having no Caddyfile site block (registry/livekit/mail/
# autodiscover - see scripts/sync_platform.py).
DOMAINS=$(python3 -c "
import sys
sys.path.insert(0, 'scripts')
from sync_platform import load_platform, DOMAINS_WITHOUT_CADDY_SITE
platform = load_platform()
domains = platform['domains']
base = domains['base']
for key, sub in domains['subdomains'].items():
    if key not in DOMAINS_WITHOUT_CADDY_SITE:
        print(f'{sub}.{base}')
")

HOSTS_BLOCK="    hosts {\n"
while IFS= read -r domain; do
  HOSTS_BLOCK+="        ${CADDY_DEV_IP} ${domain}\n"
done <<< "$DOMAINS"
HOSTS_BLOCK+="        fallthrough\n    }"

CURRENT_COREFILE=$(kubectl get configmap coredns -n kube-system -o jsonpath='{.data.Corefile}')

if echo "$CURRENT_COREFILE" | grep -qF "$MARKER_BEGIN"; then
  # Replace the existing block between the markers (idempotent re-run).
  NEW_COREFILE=$(python3 -c "
import sys
begin, end = sys.argv[1], sys.argv[2]
block = sys.argv[3]
text = sys.stdin.read()
before, _, rest = text.partition(begin)
_, _, after = rest.partition(end)
sys.stdout.write(before + begin + '\n' + block + '\n' + end + after)
" "$MARKER_BEGIN" "$MARKER_END" "$HOSTS_BLOCK" <<< "$CURRENT_COREFILE")
else
  # First run: insert right after the opening ".:53 {" of the main server
  # block - see this script's header comment on the one thing that's
  # assumed, not independently verified, about k3d's default Corefile.
  NEW_COREFILE=$(python3 -c "
import sys
begin, end = sys.argv[1], sys.argv[2]
block = sys.argv[3]
text = sys.stdin.read()
marker = '.:53 {'
idx = text.index(marker) + len(marker)
sys.stdout.write(text[:idx] + '\n' + begin + '\n' + block + '\n' + end + text[idx:])
" "$MARKER_BEGIN" "$MARKER_END" "$HOSTS_BLOCK" <<< "$CURRENT_COREFILE")
fi

kubectl create configmap coredns -n kube-system \
  --from-literal=Corefile="$NEW_COREFILE" \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl rollout restart deployment/coredns -n kube-system >/dev/null
kubectl rollout status deployment/coredns -n kube-system --timeout=60s

echo "    CoreDNS now resolves the following to caddy-dev (${CADDY_DEV_IP}):"
echo "${DOMAINS//$'\n'/$'\n'      - }" | sed '1s/^/      - /'
