#!/usr/bin/env bash
# libre365 - makes the k3d dev cluster's CoreDNS resolve every Caddy-fronted
# platform.yaml domain (sso.libre365.example.org, seafile's, etc.) to the
# in-cluster `caddy-dev` Service, instead of failing outright.
#
# Why this exists (see docs/oidc.md for the full story): every component's
# OIDC configuration (Keycloak's own KC_HOSTNAME, Seafile/Vikunja/Synapse's
# issuer/authurl, the two oauth2-proxy gates' oidc-issuer-url) uses the real
# public domain unconditionally - the SAME value in production and dev,
# deliberately never hard-coded to a dev-only alternative. In production
# that domain is populated by external-dns against real DNS; this local k3d
# cluster has none, so a pod trying to reach it (Keycloak's own discovery
# document generation, oauth2-proxy's OIDC client at startup, an app's
# server-side token exchange) would otherwise fail to resolve it at all.
#
# CoreDNS's own `hosts` plugin supports inline entries directly in the
# Corefile (no external file needed) - this is CoreDNS's own documented
# mechanism for exactly this kind of local override, not something specific
# to this repo. Idempotent: entries are written between two marker
# comments, replaced (not duplicated) on every re-run - safe to call from
# deploy.sh on every invocation, matching this directory's existing
# idempotency convention.
#
# [CORRECTED] found live on a user's VM: k3d's own default Corefile
# already declares a `hosts /etc/coredns/NodeHosts { ttl 60; reload 15s;
# fallthrough }` block in the same `.:53 { }` server block, and CoreDNS's
# `hosts` plugin can only be instantiated ONCE per server block ("plugin/
# hosts: this plugin can only be used once per Server Block" - CoreDNS's
# own real, hard limitation). This script used to insert a brand-new,
# SEPARATE `hosts { }` block, which crash-looped CoreDNS outright once the
# earlier newline-quoting bug (see git history) was fixed and stopped
# masking this. Fixed by merging our inline entries INTO the existing
# `hosts /etc/coredns/NodeHosts { ... }` block instead: the plugin's real
# syntax is `hosts [FILE [ZONES...]] { [INLINE...] no_reverse fallthrough
# [ZONES...] reload DURATION ttl DURATION }` - a FILE argument and inline
# entries are meant to coexist in the very same block (verified against
# CoreDNS's own plugin/hosts README), so no second block is needed at all.
#
# Unverified from this sandboxed environment (no live k3d cluster
# available here to actually run this against): the exact k3d/Rancher
# default Corefile layout this insertion assumes (a `hosts
# /etc/coredns/NodeHosts { ... }` block present in the main `.:53 { }`
# server block - k3d's shipped default at the time of writing) - inspect
# `kubectl get configmap coredns -n kube-system -o yaml` and adjust the
# insertion point below if a future k3d version's default Corefile differs.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

NAMESPACE="${1:-libre365}"
MARKER_BEGIN="# --- libre365-dev hosts (generated by patch-coredns-hosts.sh, do not edit) ---"
MARKER_END="# --- end libre365-dev hosts ---"

CADDY_DEV_IP=$(kubectl get service caddy-dev -n "$NAMESPACE" -o jsonpath='{.spec.clusterIP}')
if [ -z "$CADDY_DEV_IP" ]; then
  echo "    ! caddy-dev Service has no ClusterIP yet - apply infra/k8s/manifests/dev/caddy.yaml first." >&2
  exit 1
fi

# Domains read from platform.yaml (never hard-coded here) - every subdomain
# EXCEPT the ones DOMAINS_WITHOUT_CADDY_SITE already documents as
# legitimately having no Caddyfile site block (registry/livekit/mail/
# autodiscover - see scripts/sync_platform.py).
DOMAINS=$(python3 -c "
import sys
sys.path.insert(0, 'scripts')
from sync_platform import load_platform, DOMAINS_WITHOUT_CADDY_SITE
platform = load_platform()
domains = platform['domains']
base = domains['base']
for key, sub in domains['subdomains'].items():
    if key not in DOMAINS_WITHOUT_CADDY_SITE:
        print(f'{sub}.{base}')
")

# [CORRECTED] found live on a user's VM: `"...{\n"` inside a plain
# double-quoted bash string does NOT produce a real newline - it's the two
# literal characters backslash+n (bash only expands `\n` that way inside
# `$'...'` ANSI-C quoting, or via printf). CoreDNS's Corefile parser
# tokenizes on real whitespace/newlines, so the whole `hosts { ... }`
# block ended up as ONE line with literal "\n" text in it - "{\n" fused
# into a single token the parser never recognized as an opening brace,
# while the later real "}" (separated by actual spacing already in this
# script) WAS tokenized correctly - hence CoreDNS's own real error:
# "Unexpected '}' because no matching opening brace", crash-looping the
# entire cluster's DNS (not just this hosts lookup - every in-cluster
# Service name, including OpenBao's own, stopped resolving).
# Plain inline entries only (no `hosts { }` wrapper of our own - see the
# header comment above on why: they get merged into k3d's EXISTING `hosts
# /etc/coredns/NodeHosts { ... }` block instead of forming a second one).
HOSTS_LINES=""
while IFS= read -r domain; do
  HOSTS_LINES+="        ${CADDY_DEV_IP} ${domain}"$'\n'
done <<< "$DOMAINS"

CURRENT_COREFILE=$(kubectl get configmap coredns -n kube-system -o jsonpath='{.data.Corefile}')

# [CORRECTED] found live on a user's VM: a stale marker block from a
# previous (pre-fix) run was sitting right after ".:53 {" - a plain
# "replace between the markers in place" on a re-run just swapped its
# CONTENT without relocating it into the real `hosts { ... }` block,
# producing "Unknown directive '10.43.x.x'" (raw IP/hostname lines outside
# any `hosts` block are not valid Corefile syntax at all). Always strip
# any existing marker block first, unconditionally, then re-insert fresh
# at the correct location inside the existing `hosts` block - idempotent
# AND self-healing against a stale prior placement.
STRIPPED_COREFILE=$(python3 -c "
import sys
begin, end = sys.argv[1], sys.argv[2]
text = sys.stdin.read()
if begin not in text:
    sys.stdout.write(text)
else:
    before, _, rest = text.partition(begin)
    _, _, after = rest.partition(end)
    sys.stdout.write(before + after)
" "$MARKER_BEGIN" "$MARKER_END" <<< "$CURRENT_COREFILE")

# Merge our entries into the EXISTING `hosts ... { ... }` block's opening
# brace (k3d's own default `hosts /etc/coredns/NodeHosts { ttl 60; reload
# 15s; fallthrough }`) rather than declaring a second, separate `hosts`
# block - CoreDNS only allows one `hosts` plugin instantiation per server
# block. The plugin's own syntax allows a FILE argument and inline host
# entries side by side in the same block, so this is the plugin's
# intended, documented use - not a workaround.
NEW_COREFILE=$(python3 -c "
import re
import sys
begin, end = sys.argv[1], sys.argv[2]
lines = sys.argv[3]
text = sys.stdin.read()
match = re.search(r'\bhosts\b[^\n{]*\{', text)
if not match:
    sys.stderr.write('patch-coredns-hosts.sh: no existing \"hosts { ... }\" block found in the Corefile to merge into\n')
    sys.exit(1)
idx = match.end()
sys.stdout.write(text[:idx] + '\n' + begin + '\n' + lines + end + text[idx:])
" "$MARKER_BEGIN" "$MARKER_END" "$HOSTS_LINES" <<< "$STRIPPED_COREFILE")

kubectl create configmap coredns -n kube-system \
  --from-literal=Corefile="$NEW_COREFILE" \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl rollout restart deployment/coredns -n kube-system >/dev/null
kubectl rollout status deployment/coredns -n kube-system --timeout=60s

echo "    CoreDNS now resolves the following to caddy-dev (${CADDY_DEV_IP}):"
echo "${DOMAINS//$'\n'/$'\n'      - }" | sed '1s/^/      - /'
